name: opschain change
description: run an opschain change
inputs:
  opschain_apiBaseUrl:
    description: OpsChain API Base URL
    required: true
  opschain_username:
    description: OpsChain username
    required: true
  opschain_password:
    description: OpsChain password
    required: true
  opschain_project:
    description: Project code for the change
    required: true
  opschain_environment:
    description: Environment code for the change
    required: true
  opschain_action:
    description: The action to perform during this change
    required: true
  opschain_requestTimeout:
    description: opschain request timeout
    default: '60000'
    required: true
  opschain_action_metadata:
    description: The action to perform during this change
    default: ''
    required: true
  opschain_git_remote:
    description: Git Remote name
    default: 'origin'
    required: true
  opschain_git_rev:
    description: The Git revision (branch/tag/commit) for the change
    default: ${GITHUB_REF#refs/heads/}
    required: true
runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      env:
        opschain_apiBaseUrl: ${{ inputs.opschain_apiBaseUrl }}
        opschain_username: ${{ inputs.opschain_username }}
        opschain_password: ${{ inputs.opschain_password }}
        opschain_requestTimeout: ${{ inputs.opschain_requestTimeout }}
      run: |-
        echo "{ \"github_workflow\": \"${GITHUB_WORKFLOW}\", \"github_sha\": \"${GITHUB_SHA}\", \"github_repository\": \"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}\", \"github_actor\":\"${GITHUB_ACTOR}\", \"github_run_id\":\"${GITHUB_RUN_ID}\", \"workflow_run_url\":\"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\", ${{inputs.opschain_action_metadata}} }" > metadata.json
        cat ./metadata.json
        opschain change create -p ${{inputs.opschain_project}} -e ${{inputs.opschain_environment}} -G ${{inputs.opschain_git_remote}} -g ${{inputs.opschain_git_rev}} -y -a ${{inputs.opschain_action}} -m ./metadata.json