name: opschain change
description: run an opschain change
inputs:
  opschain_apiBaseUrl:
    description: opschain api base URL
    required: true
  opschain_username:
    description: opschain username
    required: true
  opschain_password:
    description: opschain password
    required: true
  opschain_project:
    description: opschain project
    required: true
  opschain_environment:
    description: opschain environment
    required: true
  opschain_action:
    description: opschain action
    required: true
  opschain_requestTimeout:
    description: opschain request timeout
    default: '60000'
    required: true
  opschain_action_metadata:
    description: opschain action metadata
    default: ''
    required: true
  opschain_remote:
    description: opschain remote
    default: 'origin'
    required: true
runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      env:
        opschain_apiBaseUrl: ${{ inputs.opschain_apiBaseUrl }}
        opschain_username: ${{ inputs.opschain_username }}
        opschain_password: ${{ inputs.opschain_password }}
        opschain_requestTimeout: ${{ inputs.opschain_requestTimeout }}
      run: |-
        echo "{ \"github_workflow\": \"${GITHUB_WORKFLOW}\", \"github_repository\": \"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}\", \"github_actor\":\"${GITHUB_ACTOR}\", \"github_run_id\":\"${GITHUB_RUN_ID}\", \"workflow_run_url\":\"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\", ${{inputs.opschain_action_metadata}} }" > metadata.json
        opschain change create -p ${{inputs.opschain_project}} -e ${{inputs.opschain_environment}} -G ${{inputs.opschain_remote}} -g ${GITHUB_REF#refs/heads/} -y -a ${{inputs.opschain_action}} -m ./metadata.json